# Generated by Django 4.1.3 on 2022-11-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=60)),
                ('sequence', models.CharField(max_length=500)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=60)),
                ('clade', models.CharField(max_length=60)),
                ('genus', models.CharField(max_length=60)),
                ('species', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('pfam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinapp.domain')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinapp.protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='protein_domains', to='proteinapp.proteindomain'),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinapp.taxonomy'),
        ),
    ]
