# Generated by Django 4.1.3 on 2022-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxa_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='proteindomain',
            unique_together={('pfam', 'protein')},
        ),
    ]
