# Generated by Django 4.1.3 on 2022-11-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0002_alter_protein_protein_id_alter_taxonomy_taxa_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proteindomain',
            unique_together=set(),
        ),
    ]
