# Generated by Django 4.1.3 on 2022-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0003_alter_proteindomain_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='taxa_id',
            field=models.CharField(max_length=60),
        ),
    ]
