# Generated by Django 4.1.3 on 2022-11-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0004_alter_taxonomy_taxa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteindomain',
            old_name='pfam',
            new_name='pfam_id',
        ),
    ]
